### ISSUE TITLE
Express oauth server doesnt start on windows

### ISSUE THREAD

**Issue by JGABREU2145** [JGABREU2145/all-in#2]
```js
C:\Users\justi\Desktop\all-in\node_modules\simple-oauth2\lib\client.js:19
  #config = null;
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\justi\Desktop\all-in\node_modules\simple-oauth2\index.js:3:16)
```

**Comment by jbakarich** [comment]
Seems to be fixed by upgrading node versions to `>12`
